export const GAME_HZ = 30;

export const RULES = {
  SMALL_DOT_SPEED_RATIO: 0.02,
  SMALL_DOT_SIZE_RATIO: 0.0625,
  SMALL_DOT_CREATE_INTERVAL: 120,
  POINT_DOT_SIZE_RATIO: 0.125,
  POINT_DOT_VALUE: 5,
  POINT_DOT_SIZE_ANIMATION_TIME: 10,
  POINT_DOT_TIME_BETWEEN: 300,
  POINT_DOT_FADE_TIME: 150,
  POINT_DOT_PULSE_SPEED: 12,
  PLAYER_DOT_SPEED_RATIO: 0.3 / (Math.PI / 2),
  PLAYER_DOT_SIZE_RATIO: 0.125,
  MAX_TIME_DIFFICULTY: 7200,
  DOT_LIMIT: 200,
  PLAYER_DOT_COLOR_INCREMENT_SMALL: 1,
  PLAYER_DOT_SIZE_INCREMENT_SMALL: 0.008,
  PLAYER_DOT_SIZE_INCREMENT_POINT: 0.02,
} as const;

export const COLOR_SET = ['#E91E63', '#2196F3', '#8BC34A'] as const;
